### ISSUE TITLE
Compatibility with haskell-src-exts 1.18.0

### ISSUE THREAD

**Issue by sjakobi** [sol/interpolate#7]
It looks like no changes are required in interpolate:

Using https://github.com/bmillwood/haskell-src-meta/pull/58 in the following stack.yaml, interpolate builds and tests just fine:

```
resolver: lts-7.2
packages:
- '.'
- location:
    git: https://github.com/ddssff/haskell-src-meta
    commit: b7c90892b9aceef874ddf5f3f9bd88b5a9b98f9f
  extra-dep: true
extra-deps:
- haskell-src-exts-1.18.0
```
